# Generated by Django 3.2.7 on 2021-10-08 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousSociety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('statute', models.FileField(upload_to='')),
                ('real_address', models.CharField(max_length=255)),
                ('legal_address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SocietyRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('observation', models.CharField(max_length=255)),
                ('file_number', models.CharField(max_length=255)),
                ('anonymous_society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anonymous_societys.anonymoussociety')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anonymous_societys.status')),
            ],
        ),
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=255)),
                ('anonymous_society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anonymous_societys.anonymoussociety')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anonymous_societys.country')),
            ],
        ),
        migrations.CreateModel(
            name='Associate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('percentage', models.IntegerField()),
                ('society_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anonymous_societys.societyregistration')),
            ],
        ),
        migrations.AddField(
            model_name='anonymoussociety',
            name='legal_representative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anonymous_societys.associate'),
        ),
    ]
