# Generated by Django 3.2.7 on 2021-10-13 00:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous_societys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='societyregistration',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anonymoussociety',
            name='date_created',
            field=models.DateField(),
        ),
    ]
