# Generated by Django 3.2.7 on 2021-10-13 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous_societys', '0003_alter_country_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societyregistration',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='anonymous_societys.status'),
        ),
    ]
