# Generated by Django 3.2.7 on 2021-10-13 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous_societys', '0004_alter_societyregistration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societyregistration',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='societyregistration',
            name='file_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='societyregistration',
            name='observation',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
