# Generated by Django 3.2.7 on 2021-10-13 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous_societys', '0005_auto_20211013_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societyregistration',
            name='anonymous_society',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anonymous_societys.anonymoussociety'),
        ),
    ]
