# Generated by Django 3.2.7 on 2021-10-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous_societys', '0007_alter_anonymoussociety_statute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymoussociety',
            name='statute',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='export',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
