# Generated by Django 3.2.7 on 2021-10-26 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous_societys', '0008_auto_20211014_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='societyregistration',
            name='hash',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='societyregistration',
            name='file_number',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
