# Generated by Django 3.2.7 on 2021-11-24 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous_societys', '0009_auto_20211026_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='societyregistration',
            name='qr',
            field=models.ImageField(null=True, upload_to='qr_images/'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='society_registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='society_registrations', to='anonymous_societys.societyregistration'),
        ),
        migrations.AlterField(
            model_name='export',
            name='anonymous_society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anonymous_society', to='anonymous_societys.anonymoussociety'),
        ),
    ]
