# Generated by Django 3.2.7 on 2021-11-24 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous_societys', '0010_auto_20211124_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societyregistration',
            name='qr',
            field=models.FileField(null=True, upload_to='qr_images/'),
        ),
    ]
