# Generated by Django 3.2.7 on 2021-11-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous_societys', '0011_alter_societyregistration_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societyregistration',
            name='qr',
            field=models.ImageField(null=True, upload_to='qr_images/'),
        ),
    ]
