# Generated by Django 3.2.7 on 2021-12-08 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous_societys', '0014_alter_associate_society_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymoussociety',
            name='legal_representative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='anonymous_societys.associate'),
        ),
    ]
