# Generated by Django 3.2.7 on 2021-12-08 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous_societys', '0015_alter_anonymoussociety_legal_representative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymoussociety',
            name='legal_representative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anonymous_societys.associate'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='society_registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='society_registrations', to='anonymous_societys.societyregistration'),
        ),
        migrations.AlterField(
            model_name='export',
            name='anonymous_society',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anonymous_society', to='anonymous_societys.anonymoussociety'),
        ),
    ]
