# Generated by Django 3.2.7 on 2021-09-30 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Associate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='AnonymousSociety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('statute', models.FileField(upload_to='')),
                ('real_address', models.CharField(max_length=255)),
                ('legal_address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('country', models.CharField(default='Argentina', max_length=128)),
                ('associates', models.ManyToManyField(related_name='anonymous_society', to='api.Associate')),
                ('legal_representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.associate')),
            ],
        ),
    ]
